HOST=localhost
PORT=5432
USER=app
DB=prisma-local
PASSWORD=mypaSsWd

psql "postgresql://root:password@$HOST:$PORT/$DB" <<-EOSQL
	CREATE USER $USER WITH PASSWORD '$PASSWORD';
	ALTER USER $USER CREATEDB;
	GRANT CREATE ON DATABASE "$DB" TO $USER;
	GRANT CREATE ON SCHEMA public TO $USER;
	GRANT DELETE, INSERT, SELECT, UPDATE ON ALL TABLES IN SCHEMA public TO $USER;
	GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO $USER;